HTML Answers
FuelFrontend/Frontend-Developer-Interview-Preparation pull request #6
Opened 2017-08-30 11:11 UTC by gokulkrishh

- Added some HTML answers

2017-08-31 14:02 UTC, logeshpaul commented on HTML/Answers/07.cookies-session-and-localstorage-storage-difference.md
> +- **Limited** storage space **4KB**(~4096B)
I think the below representation would be nice to have

**Limited** storage space **4096 bytes / ~4 kb**

2017-08-31 14:02 UTC, logeshpaul commented on HTML/Answers/07.cookies-session-and-localstorage-storage-difference.md
> +- Storage space is **more than cookies** 5MB (~5120KB)
same as above

2017-08-31 14:04 UTC, logeshpaul commented on HTML/Answers/07.cookies-session-and-localstorage-storage-difference.md
> +- Storage space is similar to **session storage**
it would be great if you mention the size here also instead of saying it's similar to session storage

2017-08-31 14:07 UTC, logeshpaul commented on HTML/Answers/09.async-defer-hidden-attributes.md
> +# 09. async, defer, hidden attributes
can you capitalize the text

2017-08-31 14:13 UTC, gokulkrishh commented
@logeshpaul Sure. Will do 👍

2017-08-31 14:14 UTC, logeshpaul commented on HTML/Answers/09.async-defer-hidden-attributes.md
> +- Browser will **pause** the **HTML parsing** to **executed** the downloded script
**execute** the downloded script ??

2017-08-31 14:15 UTC, logeshpaul commented on HTML/Answers/09.async-defer-hidden-attributes.md
> +<div hidden>I am div with hidden attribute</div>
🔥  Nice feature!

2017-08-31 14:18 UTC, logeshpaul commented on HTML/README.MD
> +- [x] - 04. Input tags and other semantic tags in [html5](Answers/02.whats-new-in-html5.md) and [5.1](Answers/03.whats-new-in-html5.1.md)
I think this we can remove, as we are referring to the same sections.

2017-08-31 14:19 UTC, gokulkrishh commented
Hehe sure will do the necessary changes. I should concentrate on spellings and grammer 👍

2017-08-31 14:19 UTC, logeshpaul requested changes
Fix few comments.

2017-09-02 07:46 UTC, logeshpaul approved these changes

2017-09-02 07:46 UTC, logeshpaul commented
@gokulkrishh good to go!

2017-09-02 09:22 UTC, gokulkrishh commented
Cool. 👍 Will merge this one and add a new PR for rest

2017-09-02 09:22 UTC, merged